[package]
name = "met-io-rs"
version = "0.1.0"
authors = ["cheng <csc00000@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.16"
byteorder = "1.3.4"
binread = "1.0.0"
